name = "json-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2014-2021, Jacob Williams"
license = "BSD"
description = "A Fortran 2008 JSON API"
homepage = "https://github.com/jacobwilliams/json-fortran"
categories = ["io"]
keywords = ["JSON"]

[build]
external-modules = "ifcore"

[library]
source-dir = "src"